In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from scipy import stats

In [2]:
data=pd.read_csv(r"C:\Users\sairam\Downloads\Lumpy skin disease data.csv")
data.head()

x          y region     country reportingDate   cld   dtr    frs  \
0  90.380931  22.437184   Asia  Bangladesh     10/9/2020  41.6  12.8   0.00   
1  87.854975  22.986757   Asia       India    20/12/2019  40.5  13.3   0.00   
2  85.279935  23.610181   Asia       India    20/12/2019  27.3  13.6   0.08   
3  81.564510  43.882221   Asia       China    25/10/2019  45.3  12.8  31.00   
4  81.161057  43.834976   Asia       China    25/10/2019  38.8  13.2  31.00   

   pet   pre   tmn   tmp   tmx   vap   wet  elevation  dominant_land_cover  \
0  2.3   1.7  12.7  19.1  25.5  15.7  0.00        147                    2   
1  2.4   0.0  13.2  19.8  26.5  16.3  0.00        145                    2   
2  2.3   0.6   9.4  16.2  23.0  13.0  0.98        158                    2   
3  0.4   8.8 -22.5 -16.1  -9.7   0.9  4.64        178                    2   
4  0.4  10.5 -20.4 -13.8  -7.2   1.2  1.69        185                    3   

   X5_Ct_2010_Da  X5_Bf_2010_Da  lumpy  
0   27970.983100    3691.746950      1  
1   25063.646690     671.326701      1  
2    6038.477155    1426.839831      1  
3     760.703340       0.000000      1  
4     270.367426       0.000000      1

In [3]:
data=data.drop(['region','country','reportingDate'],axis=1)
data.head()

x          y   cld   dtr    frs  pet   pre   tmn   tmp   tmx   vap  \
0  90.380931  22.437184  41.6  12.8   0.00  2.3   1.7  12.7  19.1  25.5  15.7   
1  87.854975  22.986757  40.5  13.3   0.00  2.4   0.0  13.2  19.8  26.5  16.3   
2  85.279935  23.610181  27.3  13.6   0.08  2.3   0.6   9.4  16.2  23.0  13.0   
3  81.564510  43.882221  45.3  12.8  31.00  0.4   8.8 -22.5 -16.1  -9.7   0.9   
4  81.161057  43.834976  38.8  13.2  31.00  0.4  10.5 -20.4 -13.8  -7.2   1.2   

    wet  elevation  dominant_land_cover  X5_Ct_2010_Da  X5_Bf_2010_Da  lumpy  
0  0.00        147                    2   27970.983100    3691.746950      1  
1  0.00        145                    2   25063.646690     671.326701      1  
2  0.98        158                    2    6038.477155    1426.839831      1  
3  4.64        178                    2     760.703340       0.000000      1  
4  1.69        185                    3     270.367426       0.000000      1

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24803 entries, 0 to 24802
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   x                    24803 non-null  float64
 1   y                    24803 non-null  float64
 2   cld                  24803 non-null  float64
 3   dtr                  24803 non-null  float64
 4   frs                  24803 non-null  float64
 5   pet                  24803 non-null  float64
 6   pre                  24803 non-null  float64
 7   tmn                  24803 non-null  float64
 8   tmp                  24803 non-null  float64
 9   tmx                  24803 non-null  float64
 10  vap                  24803 non-null  float64
 11  wet                  24803 non-null  float64
 12  elevation            24803 non-null  int64  
 13  dominant_land_cover  24803 non-null  int64  
 14  X5_Ct_2010_Da        24803 non-null  float64
 15  X5_Bf_2010_Da        24803 non-null 

In [5]:
data.describe()

x             y           cld           dtr           frs  \
count  24803.000000  24803.000000  24803.000000  24803.000000  24803.000000   
mean      79.221374     46.370056     59.452159      9.107777     23.978048   
std       43.338530     19.220555     19.423029      2.988448     11.518315   
min     -179.750000    -28.750000      0.000000      2.000000      0.000000   
25%       45.083150     34.750000     43.800000      6.800000     23.210000   
50%       80.750000     48.250000     62.300000      8.300000     31.000000   
75%      109.750000     61.750000     75.300000     11.100000     31.000000   
max      179.750000     81.750000     98.700000     20.600000     31.000000   

                pet           pre           tmn           tmp           tmx  \
count  24803.000000  24803.000000  24803.000000  24803.000000  24803.000000   
mean       0.803487     26.271137    -15.794755    -11.227807     -6.681212   
std        1.172915     33.630747     17.587685     17.989715     18.540915   
min        0.000000      0.000000    -52.100000    -48.100000    -44.200000   
25%        0.000000      5.900000    -30.100000    -25.500000    -20.900000   
50%        0.200000     14.700000    -19.100000    -14.200000     -9.700000   
75%        1.100000     33.400000     -2.200000      1.400000      4.900000   
max        7.500000    341.900000     23.900000     28.500000     36.400000   

                vap           wet     elevation  dominant_land_cover  \
count  24803.000000  24803.000000  24803.000000         24803.000000   
mean       3.728230      8.542482    164.769302             4.416119   
std        4.952353      6.205199     19.679197             2.406231   
min        0.000000      0.000000     66.000000             0.000000   
25%        0.400000      3.000000    152.000000             3.000000   
50%        1.500000      8.020000    161.000000             4.000000   
75%        4.800000     12.710000    176.000000             4.000000   
max       28.600000     30.920000    249.000000            11.000000   

       X5_Ct_2010_Da  X5_Bf_2010_Da         lumpy  
count   24803.000000   24803.000000  24803.000000  
mean      629.129412     170.306057      0.122526  
std      2279.198775    1127.977653      0.327898  
min         0.000000       0.000000      0.000000  
25%         2.513366       0.000000      0.000000  
50%        43.383823       0.000197      0.000000  
75%       386.124908       0.002094      0.000000  
max    167388.672700   56654.780150      1.000000

In [6]:
data.isnull().sum()

x                      0
y                      0
cld                    0
dtr                    0
frs                    0
pet                    0
pre                    0
tmn                    0
tmp                    0
tmx                    0
vap                    0
wet                    0
elevation              0
dominant_land_cover    0
X5_Ct_2010_Da          0
X5_Bf_2010_Da          0
lumpy                  0
dtype: int64

In [7]:
data=data.fillna(data.mean())
data.isnull().sum()

x                      0
y                      0
cld                    0
dtr                    0
frs                    0
pet                    0
pre                    0
tmn                    0
tmp                    0
tmx                    0
vap                    0
wet                    0
elevation              0
dominant_land_cover    0
X5_Ct_2010_Da          0
X5_Bf_2010_Da          0
lumpy                  0
dtype: int64

In [8]:
data.duplicated()
data=data.drop_duplicates()
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23726 entries, 0 to 24802
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   x                    23726 non-null  float64
 1   y                    23726 non-null  float64
 2   cld                  23726 non-null  float64
 3   dtr                  23726 non-null  float64
 4   frs                  23726 non-null  float64
 5   pet                  23726 non-null  float64
 6   pre                  23726 non-null  float64
 7   tmn                  23726 non-null  float64
 8   tmp                  23726 non-null  float64
 9   tmx                  23726 non-null  float64
 10  vap                  23726 non-null  float64
 11  wet                  23726 non-null  float64
 12  elevation            23726 non-null  int64  
 13  dominant_land_cover  23726 non-null  int64  
 14  X5_Ct_2010_Da        23726 non-null  float64
 15  X5_Bf_2010_Da        23726 non-null 

In [9]:
z = np.abs(stats.zscore(data['cld']))
out=np.where(z>3)[0]
print('cld'+ " "+str(out))
data['cld']=data['cld'].drop(out)

cld [17665]


In [10]:
z = np.abs(stats.zscore(data['dtr']))
out=np.where(z>3)[0]
print('dtr'+ " "+str(out))
data['dtr']=data['dtr'].drop(out)

dtr [17840 17841 17842 17843 17856 17857 17858 17859 17872 17873 17874 17875
 17889 19403 19437 19438 19441 19442 19443 19444 19472 19473 19474 19475
 19476 19477 19478 19479 19480 19481 19510 19609 19610 19664 19665 19827
 20683 20691 20697 22055 22056 22057 22100 22101 22102 22103 22144 22145
 22146 22147 22148 22187 22188 22189 22190 22191 22192 22233 22234 22235
 22236 22237 22238 22279 22280 22281 22282 22283 22284 22324 22325 22326
 22327 22328 22329 22371 22372 22373 22374 22375 22420 22421 22422 22423
 22470 22471]


In [11]:
z = np.abs(stats.zscore(data['frs']))
out=np.where(z>3)[0]
print('frs'+ " "+str(out))
data['frs']=data['frs'].drop(out)

frs []


In [12]:
z = np.abs(stats.zscore(data['tmn']))
out=np.where(z>3)[0]
print('tmn'+ " "+str(out))
data['tmn']=data['tmn'].drop(out)

tmn []


In [13]:
z = np.abs(stats.zscore(data['tmp']))
out=np.where(z>3)[0]
print('tmp'+ " "+str(out))
data['tmp']=data['tmp'].drop(out)

tmp []


In [14]:
z = np.abs(stats.zscore(data['tmx']))
out=np.where(z>3)[0]
print('tmx'+ " "+str(out))
data['tmx']=data['tmx'].drop(out)

tmx []


In [15]:
z = np.abs(stats.zscore(data['wet']))
out=np.where(z>3)[0]
print('wet'+ " "+str(out))
data['wet']=data['wet'].drop(out)

wet [23240 23255 23256]


In [16]:
z = np.abs(stats.zscore(data['dominant_land_cover']))
out=np.where(z>3)[0]
print('dominant_land_cover'+ " "+str(out))
data['dominant_land_cover']=data['dominant_land_cover'].drop(out)

dominant_land_cover []


In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 23726 entries, 0 to 24802
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   x                    23726 non-null  float64
 1   y                    23726 non-null  float64
 2   cld                  23725 non-null  float64
 3   dtr                  23640 non-null  float64
 4   frs                  23726 non-null  float64
 5   pet                  23726 non-null  float64
 6   pre                  23726 non-null  float64
 7   tmn                  23726 non-null  float64
 8   tmp                  23726 non-null  float64
 9   tmx                  23726 non-null  float64
 10  vap                  23726 non-null  float64
 11  wet                  23723 non-null  float64
 12  elevation            23726 non-null  int64  
 13  dominant_land_cover  23726 non-null  int64  
 14  X5_Ct_2010_Da        23726 non-null  float64
 15  X5_Bf_2010_Da        23726 non-null 

In [18]:
data.isnull().sum()

x                       0
y                       0
cld                     1
dtr                    86
frs                     0
pet                     0
pre                     0
tmn                     0
tmp                     0
tmx                     0
vap                     0
wet                     3
elevation               0
dominant_land_cover     0
X5_Ct_2010_Da           0
X5_Bf_2010_Da           0
lumpy                   0
dtype: int64

In [19]:
data=data.fillna(method='bfill')
data.isnull().sum()

x                      0
y                      0
cld                    0
dtr                    0
frs                    0
pet                    0
pre                    0
tmn                    0
tmp                    0
tmx                    0
vap                    0
wet                    0
elevation              0
dominant_land_cover    0
X5_Ct_2010_Da          0
X5_Bf_2010_Da          0
lumpy                  0
dtype: int64

In [20]:
for column in data.columns:
    data[column] = (data[column] - data[column].min()) / (data[column].max() - data[column].min()) 
data.head()

x         y       cld       dtr       frs       pet       pre  \
0  0.751407  0.463232  0.421479  0.580645  0.000000  0.306667  0.004972   
1  0.744381  0.468206  0.410334  0.607527  0.000000  0.320000  0.000000   
2  0.737218  0.473848  0.276596  0.623656  0.002581  0.306667  0.001755   
3  0.726883  0.657305  0.458967  0.580645  1.000000  0.053333  0.025739   
4  0.725761  0.656878  0.393110  0.602151  1.000000  0.053333  0.030711   

        tmn       tmp       tmx       vap       wet  elevation  \
0  0.852632  0.877285  0.864764  0.548951  0.000000   0.442623   
1  0.859211  0.886423  0.877171  0.569930  0.000000   0.431694   
2  0.809211  0.839426  0.833747  0.454545  0.031695   0.502732   
3  0.389474  0.417755  0.428040  0.031469  0.150065   0.612022   
4  0.417105  0.447781  0.459057  0.041958  0.054657   0.650273   

   dominant_land_cover  X5_Ct_2010_Da  X5_Bf_2010_Da  lumpy  
0             0.181818       0.167102       0.065162    1.0  
1             0.181818       0.149733       0.011849    1.0  
2             0.181818       0.036075       0.025185    1.0  
3             0.181818       0.004545       0.000000    1.0  
4             0.272727       0.001615       0.000000    1.0

In [21]:
x = data.iloc[:,:-1]
y = data.iloc[: ,-1]
y

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
        ... 
24798    0.0
24799    0.0
24800    0.0
24801    0.0
24802    0.0
Name: lumpy, Length: 23726, dtype: float64

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,stratify=y)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(21353, 16)
(21353,)
(2373, 16)
(2373,)


In [23]:
from sklearn.svm import SVC
# Building a Support Vector Machine on train data
svc_model = SVC(kernel='rbf',gamma=8)
svc_model.fit(x_train, y_train)

SVC(gamma=8)

In [24]:
from sklearn.metrics import accuracy_score, confusion_matrix
predictions= svc_model .predict(x_train)
percentage=svc_model.score(x_train,y_train)
res=confusion_matrix(y_train,predictions)
print("Training confusion matrix")
print(res)
predictions= svc_model .predict(x_test)
percentage=svc_model.score(x_test,y_test)
res=confusion_matrix(y_test,predictions)
print("validation confusion matrix")
print(res)
# check the accuracy on the training set
print('training accuracy = '+str(svc_model.score(x_train, y_train)*100))
print('testing accuracy = '+str(svc_model.score(x_test, y_test)*100))

Training confusion matrix
[[19329   258]
 [  456  1310]]
validation confusion matrix
[[2152   25]
 [  51  145]]
training accuracy = 96.65620755865686
testing accuracy = 96.79730299199326


In [25]:
data['lumpy'].value_counts()
df_class_1=data[data['lumpy']==1]
df_class_0=data[data['lumpy']==0]

In [26]:
df_class_1_over = df_class_1.sample(21764, replace=True)
df_test_over = pd.concat([df_class_0, df_class_1_over], axis=0)

In [27]:
df_test_over.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 43528 entries, 3039 to 2545
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   x                    43528 non-null  float64
 1   y                    43528 non-null  float64
 2   cld                  43528 non-null  float64
 3   dtr                  43528 non-null  float64
 4   frs                  43528 non-null  float64
 5   pet                  43528 non-null  float64
 6   pre                  43528 non-null  float64
 7   tmn                  43528 non-null  float64
 8   tmp                  43528 non-null  float64
 9   tmx                  43528 non-null  float64
 10  vap                  43528 non-null  float64
 11  wet                  43528 non-null  float64
 12  elevation            43528 non-null  float64
 13  dominant_land_cover  43528 non-null  float64
 14  X5_Ct_2010_Da        43528 non-null  float64
 15  X5_Bf_2010_Da        43528 non-nul

In [28]:
y1=df_test_over['lumpy']
df_test_over=df_test_over.drop(['lumpy'],axis=1)
X1=df_test_over

In [29]:
from sklearn.model_selection import train_test_split

X1_train,X1_test ,y1_train, y1_test = train_test_split(X1,y1,
                                                   test_size=0.2,
                                                   random_state=0,
                                                  shuffle = True,
                                                  stratify = y1)

print('training data shape is :{}.'.format(X1_train.shape))
print('training label shape is :{}.'.format(y1_train.shape))
print('testing data shape is :{}.'.format(X1_test.shape))
print('testing label shape is :{}.'.format(y1_test.shape))

training data shape is :(34822, 16).
training label shape is :(34822,).
testing data shape is :(8706, 16).
testing label shape is :(8706,).


In [30]:
from sklearn.svm import SVC
svc_model = SVC(kernel='rbf',gamma=8)
svc_model.fit(X1_train, y1_train)

SVC(gamma=8)

In [31]:
from sklearn.metrics import accuracy_score, confusion_matrix
predictions= svc_model .predict(X1_train)
percentage=svc_model.score(X1_train,y1_train)
res=confusion_matrix(y1_train,predictions)
print("Training confusion matrix")
print(res)
predictions= svc_model .predict(X1_test)
percentage=svc_model.score(X1_test,y1_test)
res=confusion_matrix(y1_test,predictions)
print("validation confusion matrix")
print(res)
# check the accuracy on the training set
print('training accuracy = '+str(svc_model.score(X1_train, y1_train)*100))
print('testing accuracy = '+str(svc_model.score(X1_test, y1_test)*100))

Training confusion matrix
[[16141  1270]
 [  513 16898]]
validation confusion matrix
[[4036  317]
 [ 150 4203]]
training accuracy = 94.87967376945609
testing accuracy = 94.63588329887433


In [ ]:
from sklearn.svm import SVC
svc_model = SVC(kernel='poly',gamma=8)
svc_model.fit(X1_train, y1_train)